# MegaLinter Configuration
# https://megalinter.github.io/

# Core Configuration
APPLY_FIXES: yes
DISABLE_ERRORS: false
SHOW_ELAPSED_TIME: true
PARALLEL: true
FILEIO_REPORTER: false

# Linters Configuration
DISABLE:
  - COPYPASTE # Disable copy-paste detection

DISABLE_LINTERS:
  - JSON_PRETTIER # Disable beautifying JSON with Prettier
  - YAML_PRETTIER # Disable beautifying YAML with Prettier

# Not worried if Lychee finds dead links
SPELL_LYCHEE_DISABLE_ERRORS: true

# Some Python Lint tools will fail without requirements installed
PRE_COMMANDS:
  - command: python3 -m pip install --no-cache-dir -e ".[dev]"
    venv: pylint
    continue_if_failed: false
  - command: python3 -m pip install --no-cache-dir -e ".[dev]"
    venv: pyright
    continue_if_failed: false

# Python Configuration
PYTHON_BLACK_ARGUMENTS: "--line-length 88"
PYTHON_ISORT_ARGUMENTS: "--profile black"
PYTHON_FLAKE8_ARGUMENTS: "--max-line-length=88"
PYTHON_MYPY_ARGUMENTS: "--ignore-missing-imports"

# JSON Configuration
# --bom               Ignore the leading UTF-8 byte-order mark
# --comments          Allow comments in JSON files
# --trailing-newline  Ensure a trailing newline at the end of JSON files
# --trailing-commas   Allow trailing commas in JSON files
JSON_JSONLINT_ARGUMENTS: "--comments --trailing-newline --trailing-commas"

# CSpell Config
SPELL_CSPELL_FILTER_REGEX_EXCLUDE: (\.cspell\.json|\.gitignore)

# Filter Configuration
FILTER_REGEX_EXCLUDE: (\.git|\.github|\.venv|\.pytest_cache|\.vscode|__pycache__)
