---
# Hooks to use in this repository
repos:
  ########################################
  # Beautifiers and Formatters
  ########################################

  # Sort all Python import statements
  - repo: https://github.com/pycqa/isort
    rev: 9.0.1
    hooks:
      - id: isort
        name: isort (Python)
        args: [--profile, black]

  # Automatically fix outdated Python syntax
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        name: pyupgrade (Python)
        args: [--py310-plus, --keep-runtime-typing]

  # Beautify Python
  - repo: https://github.com/psf/black
    rev: 26.5.1
    hooks:
      - id: black
        name: black (Python)

  ########################################
  # Linters to validate beautifiers output
  ########################################
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-illegal-windows-names
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: name-tests-test
        args: [--pytest-test-first]
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
